import { useState,useEffect } from "react";
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api} from '../services/api';
import type {DriveStore,DriveCart,DriveProduct,DriveProposal,DriveJob} from '../../shared/drive';
import {useApp} from '../hooks/app';
type Prepared={id:string;mode:string;proposals:DriveProposal[]};
const money=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n);
export function DrivePanel({week}:{week:string}){
  const {toast,online}=useApp(),client=useQueryClient();
  const [search,setSearch]=useState('69140 Rillieux-la-Pape'),[found,setFound]=useState<{query:string;stores:DriveStore[]}|null>(null),[prepared,setPrepared]=useState<Prepared|null>(null),[jobId,setJobId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[changing,setChanging]=useState(''),[productSearch,setProductSearch]=useState('');
  const status=useQuery({queryKey:['drive-status'],queryFn:()=>api<{mode:string;store:DriveStore|null;connected:boolean}>('/api/drive/leclerc/status')});
  const cart=useQuery({queryKey:['drive-cart'],queryFn:()=>api<DriveCart>('/api/drive/leclerc/cart'),enabled:Boolean(status.data?.store),refetchInterval:15000});
  const job=useQuery({queryKey:['drive-job',jobId],queryFn:()=>api<DriveJob>(`/api/drive/leclerc/jobs/${jobId}`),enabled:Boolean(jobId),refetchInterval:q=>q.state.data?.status==='adding_to_cart'?1000:false});
  useEffect(()=>{if(job.data&&job.data.status!=='adding_to_cart')void client.invalidateQueries({queryKey:['drive-cart']});},[job.data,client]);
  async function run(action:()=>Promise<void>){if(!online){setError('Reconnectez-vous pour utiliser le Drive.');return;}setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Le Drive est indisponible.');}finally{setBusy(false);}}
  const store=status.data?.store,mode=status.data?.mode,rows=prepared?.proposals??[];
  const total=rows.reduce((sum,r)=>sum+(r.products.find(p=>p.id===r.productId)?.price??0)*r.quantity,0);
  function updateRow(id:string,patch:Partial<DriveProposal>){setPrepared(previous=>previous?{...previous,proposals:previous.proposals.map(r=>r.ingredientId===id?{...r,...patch}:r)}:null);}
  return <section className="drive-panel">
    <h2>E.Leclerc Drive</h2>
    <p>Relisez chaque correspondance avant de préparer le panier. Créneau, commande et paiement restent sur le site officiel.</p>
    {mode==='mock'&&<p className="portions-note" role="status"><strong>Mode démonstration</strong> · Magasins, produits, prix et stocks fictifs pour tester le parcours. Aucun ajout chez E.Leclerc.</p>}
    {mode==='live'&&<p className="small-note">Connecteur expérimental, non officiel. Le catalogue et les prix proviennent de votre Drive.</p>}
    {status.error&&<p role="alert" className="form-error">{status.error.message}</p>}
    {error&&<p role="alert" className="form-error">{error}</p>}
    <form className="drive-actions" onSubmit={e=>{e.preventDefault();void run(async()=>{const stores=await api<DriveStore[]>(`/api/drive/leclerc/stores?q=${encodeURIComponent(search)}`);setFound({query:search,stores});});}}>
      <label className="field">Ville ou code postal<input required minLength={2} maxLength={120} value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="button secondary" disabled={busy||Boolean(jobId&&job.data?.status==='adding_to_cart')}>Rechercher un Drive</button>
    </form>
    {found&&<div>{found.stores.length===0&&<p>Aucun Drive trouvé.</p>}{found.stores.map(s=><div className="drive-product" key={s.id}><strong>{s.name}</strong><span>{s.postalCode} {s.city}</span><button className="button secondary" disabled={busy||job.data?.status==='adding_to_cart'} onClick={()=>void run(async()=>{await api('/api/drive/leclerc/store','POST',{storeId:s.id,query:found.query});setPrepared(null);setJobId('');setFound(null);await client.invalidateQueries({queryKey:['drive-status']});await client.invalidateQueries({queryKey:['drive-cart']});})}>Choisir ce Drive</button></div>)}</div>}
    {store&&<><h3>Votre Drive</h3><p>{store.name}</p><button className="button" disabled={busy||job.data?.status==='adding_to_cart'} onClick={()=>void run(async()=>{setPrepared(await api<Prepared>('/api/drive/leclerc/prepare','POST',{week}));setJobId('');})}>{busy?'Préparation…':'Préparer depuis les courses restantes'}</button></>}
    {prepared&&<><h3>Les correspondances à valider</h3>{rows.map(row=><div className="drive-product" key={row.ingredientId}>
      <strong>{row.ingredient} · {row.needed} {row.unit}</strong><small>{row.reason}</small>
      <label className="field">Produit pour {row.ingredient}<select value={row.productId??''} disabled={Boolean(jobId)} onChange={e=>{const p=row.products.find(p=>p.id===e.target.value);const scale=(u:string)=>u==='kg'||u==='l'?1000:1;updateRow(row.ingredientId,{productId:p?.id??null,quantity:p?Math.ceil(row.needed*scale(row.unit)/(p.packQuantity*scale(p.packUnit))):1});}}><option value="">Ne pas ajouter cet ingrédient</option>{row.products.map(p=><option key={p.id} value={p.id} disabled={!p.available}>{p.name} · {p.packQuantity} {p.packUnit} · {money(p.price)}{!p.available?' · indisponible':''}</option>)}</select></label>
      {row.productId&&<label className="field">Nombre de paquets pour {row.ingredient}<input type="number" min={1} max={100} value={row.quantity} disabled={Boolean(jobId)} onChange={e=>updateRow(row.ingredientId,{quantity:Number(e.target.value)})}/></label>}
      <button className="text-button" disabled={Boolean(jobId)} onClick={()=>{setChanging(row.ingredientId);setProductSearch(row.ingredient);}}>Chercher un autre produit</button>
      {changing===row.ingredientId&&<form className="drive-actions" onSubmit={e=>{e.preventDefault();void run(async()=>{const products=await api<DriveProduct[]>(`/api/drive/leclerc/products?q=${encodeURIComponent(productSearch)}`);updateRow(row.ingredientId,{products:[...new Map([...row.products,...products].map(p=>[p.id,p])).values()],reason:products.length?'Choisissez le produit dans la liste.':'Aucun produit trouvé.'});setChanging('');});}}><label className="field">Recherche produit<input required minLength={2} value={productSearch} onChange={e=>setProductSearch(e.target.value)}/></label><button className="button secondary" disabled={busy}>Chercher</button></form>}
    </div>)}<p><strong>Total {mode==='mock'?'de démonstration':'estimé'} : {money(total)}</strong></p><p>{rows.filter(r=>!r.productId).length} ingrédient(s) à vérifier.</p>
      <button className="button" disabled={busy||Boolean(jobId)||!rows.some(r=>r.productId)||rows.some(r=>r.productId&&(!Number.isInteger(r.quantity)||r.quantity<1||r.quantity>100))} onClick={()=>void run(async()=>{const created=await api<DriveJob>('/api/drive/leclerc/prepare/confirm','POST',{id:prepared.id,items:rows.filter(r=>r.productId).map(r=>({ingredientId:r.ingredientId,productId:r.productId,quantity:r.quantity}))});setJobId(created.id);toast(mode==='mock'?'Préparation du panier de démonstration.':'Ajout des produits validés au panier.');})}>{mode==='mock'?'Valider le panier de démonstration':'Valider et ajouter au panier Leclerc'}</button>
    </>}
    {job.data&&<div role="status"><h3>{job.data.status==='adding_to_cart'?'Préparation du panier':job.data.status==='completed'?'Panier prêt':'Panier à vérifier'}</h3><p>{job.data.processed} / {job.data.total} produits traités · {job.data.success} ajoutés</p><progress max={job.data.total} value={job.data.processed}/>{job.data.failures.map((s,n)=><p key={n}>{s}</p>)}</div>}
    {cart.data&&<><h3>{mode==='mock'?'Panier de démonstration':'Votre panier Leclerc'} · {money(cart.data.totalPrice)}</h3>{cart.data.items.map(item=><div className="drive-product" key={item.productId}><strong>{item.name}</strong><span>{money(item.unitPrice)} / paquet · {money(item.totalPrice)}</span><div className="drive-actions"><button className="button secondary" aria-label={`Diminuer ${item.name}`} disabled={busy||job.data?.status==='adding_to_cart'} onClick={()=>void run(async()=>{await api(`/api/drive/leclerc/cart/items/${item.productId}`,'PATCH',{quantity:item.quantity-1});await cart.refetch();})}>−</button><span>{item.quantity}</span><button className="button secondary" aria-label={`Augmenter ${item.name}`} disabled={busy||job.data?.status==='adding_to_cart'} onClick={()=>void run(async()=>{await api(`/api/drive/leclerc/cart/items/${item.productId}`,'PATCH',{quantity:item.quantity+1});await cart.refetch();})}>+</button><button className="text-button" disabled={busy||job.data?.status==='adding_to_cart'} onClick={()=>void run(async()=>{await api(`/api/drive/leclerc/cart/items/${item.productId}`,'DELETE');await cart.refetch();})}>Retirer</button></div></div>)}</>}
    {mode==='live'&&store?.host&&<a className="button secondary" href={`https://${store.host}/`} target="_blank" rel="noreferrer">Ouvrir E.Leclerc Drive</a>}
  </section>;
}
