import type { Recipe, Ingredient, Season } from "./types.js";
import { normalize } from "./domain.js";
const seasons: Record<string, Season[]> = {
  all: ["hiver", "printemps", "été", "automne"],
  cold: ["automne", "hiver"],
  warm: ["printemps", "été"],
  spring: ["printemps"],
  summer: ["été"],
  autumn: ["automne"],
  winter: ["hiver"],
};
const months: Record<string, number[]> = {
  all: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  cold: [1, 2, 3, 9, 10, 11, 12],
  warm: [4, 5, 6, 7, 8, 9],
  spring: [3, 4, 5, 6],
  summer: [6, 7, 8, 9],
  autumn: [9, 10, 11],
  winter: [1, 2, 12],
};
const categoryNames = [
  "Fruits et légumes",
  "Viande",
  "Poisson",
  "Crèmerie",
  "Épicerie",
  "Féculents",
  "Conserves",
  "Produits frais",
];
// Format compact du catalogue : nom / quantité / unité / rayon. Quantités pour 4 adultes.
function ingredients(raw: string): Ingredient[] {
  return raw.split(";").map((s) => {
    const [name, quantity, unit, category] = s.split("/");
    return {
      name,
      quantity: Number(quantity),
      unit,
      category: categoryNames[Number(category)],
    };
  });
}
const allergenWords: Record<string, string[]> = {
  gluten: [
    "pates",
    "spaghetti",
    "lasagnes",
    "semoule",
    "boulgour",
    "pain",
    "chapelure",
    "farine",
    "pate brisee",
    "pate feuilletee",
    "nouilles",
    "sauce soja",
    "tortillas",
    "gnocchis",
  ],
  lait: [
    "lait",
    "creme",
    "beurre",
    "comte",
    "emmental",
    "parmesan",
    "mozzarella",
    "reblochon",
    "feta",
    "yaourt",
    "fromage",
    "ricotta",
  ],
  œufs: ["œuf"],
  poisson: ["saumon", "cabillaud", "colin", "thon", "truite"],
  soja: ["sauce soja", "tofu"],
  moutarde: ["moutarde"],
  céleri: ["celeri"],
  sésame: ["sesame"],
  "fruits à coque": ["amandes", "noix", "pignons"],
};
function recipe(
  id: string,
  name: string,
  description: string,
  prep: number,
  cook: number,
  season: string,
  protein: string,
  starch: string,
  style: string,
  raw: string,
  steps: string,
  light = true,
): Recipe {
  const list = ingredients(raw);
  const image =
    style === "soupe"
      ? "soup"
      : starch === "pâtes"
        ? "pasta"
        : protein === "poisson"
          ? "fish"
          : style === "salade"
            ? "salad"
            : ["gratin", "tarte"].includes(style)
              ? "bake"
              : protein === "végétarien"
                ? "vegetables"
                : "stew";
  return {
    id,
    name,
    description,
    preparationTime: prep,
    cookingTime: cook,
    totalTime: prep + cook,
    difficulty: prep > 25 ? "Intermédiaire" : "Facile",
    image: `/images/${image}.svg`,
    ingredients: list,
    instructions: steps.split("|"),
    categories: [protein, style, starch].filter((x) => x !== "aucun"),
    seasons: seasons[season],
    months: months[season],
    allergens: Object.entries(allergenWords)
      .filter(([allergen, words]) =>
        list.some(
          (i) =>
            !(allergen === "lait" && normalize(i.name) === "lait de coco") &&
            words.some((w) => normalize(i.name).includes(w)),
        ),
      )
      .map(([allergen]) => allergen),
    childFriendly: true,
    vegetarian: protein === "végétarien",
    servings: 4,
    protein,
    starch,
    style,
    light,
    createdAt: "2026-10-05T00:00:00.000Z",
    updatedAt: "2026-10-05T00:00:00.000Z",
  };
}
export const RECIPES: Recipe[] = [
  recipe(
    "hachis-parmentier",
    "Hachis parmentier",
    "Une purée moelleuse et un bœuf doucement mijoté, le classique des tablées familiales.",
    25,
    30,
    "cold",
    "bœuf",
    "pommes de terre",
    "gratin",
    "Pommes de terre/900/g/0;Bœuf haché/500/g/1;Oignons/150/g/0;Lait/200/ml/3;Beurre/30/g/3;Emmental/60/g/3;Huile d’olive/15/ml/4",
    "Épluchez les pommes de terre et faites-les cuire 20 minutes dans l’eau frémissante.|Émincez l’oignon. Faites-le revenir 5 minutes dans l’huile, ajoutez le bœuf et cuisez 8 minutes en émiettant.|Égouttez les pommes de terre. Écrasez-les avec le lait chaud et le beurre.|Étalez la viande dans un plat, recouvrez de purée puis d’emmental. Enfournez 20 minutes à 200 °C.",
    false,
  ),
  recipe(
    "poulet-roti",
    "Poulet rôti aux légumes",
    "Le rendez-vous du dimanche, avec ses légumes dorés au jus de cuisson.",
    20,
    75,
    "cold",
    "poulet",
    "pommes de terre",
    "rôti",
    "Poulet entier/1400/g/1;Pommes de terre/700/g/0;Carottes/500/g/0;Oignons/150/g/0;Huile d’olive/30/ml/4;Thym/2/g/4",
    "Préchauffez le four à 190 °C. Épluchez les légumes et coupez-les en morceaux réguliers.|Déposez le poulet dans un grand plat. Entourez-le des légumes, arrosez d’huile et parsemez de thym.|Enfournez 75 minutes en arrosant toutes les 20 minutes avec le jus et un peu d’eau si nécessaire.|Vérifiez que la partie la plus épaisse du poulet atteint 74 °C. Laissez reposer 10 minutes avant de découper.",
  ),
  recipe(
    "gratin-dauphinois",
    "Gratin dauphinois & salade",
    "Des pommes de terre fondantes, une pointe d’ail et une salade croquante.",
    20,
    60,
    "cold",
    "végétarien",
    "pommes de terre",
    "gratin",
    "Pommes de terre/1000/g/0;Lait/300/ml/3;Crème/200/ml/3;Ail/8/g/0;Salade verte/200/g/0;Huile d’olive/20/ml/4;Vinaigre/10/ml/4",
    "Préchauffez le four à 170 °C. Épluchez les pommes de terre et coupez-les en fines rondelles sans les rincer.|Frottez le plat avec l’ail, puis disposez les rondelles. Mélangez lait et crème et versez dans le plat.|Enfournez 60 minutes, jusqu’à ce qu’un couteau traverse facilement les pommes de terre.|Lavez la salade et assaisonnez-la d’huile et de vinaigre au moment de servir.",
    false,
  ),
  recipe(
    "lasagnes",
    "Lasagnes à la bolognaise",
    "Une sauce tomate maison, des couches généreuses et un dessus gratiné.",
    25,
    45,
    "all",
    "bœuf",
    "pâtes",
    "gratin",
    "Lasagnes/250/g/5;Bœuf haché/400/g/1;Tomates concassées/600/g/6;Oignons/150/g/0;Carottes/150/g/0;Lait/500/ml/3;Farine/40/g/4;Beurre/40/g/3;Emmental/80/g/3;Huile d’olive/15/ml/4",
    "Hachez oignon et carotte. Faites-les revenir dans l’huile 5 minutes, puis ajoutez le bœuf et cuisez 5 minutes.|Ajoutez les tomates et laissez mijoter 15 minutes. Préchauffez le four à 180 °C.|Faites fondre le beurre, ajoutez la farine, puis le lait progressivement. Fouettez 5 minutes pour épaissir.|Alternez sauce, lasagnes et béchamel dans un plat. Terminez par le fromage et enfournez 30 minutes.",
    false,
  ),
  recipe(
    "spaghetti-bolognaise",
    "Spaghetti bolognaise",
    "Une sauce à la tomate et aux carottes qui plaît aux petits comme aux grands.",
    15,
    25,
    "all",
    "bœuf",
    "pâtes",
    "poêlée",
    "Spaghetti/350/g/5;Bœuf haché/400/g/1;Tomates concassées/500/g/6;Carottes/200/g/0;Oignons/150/g/0;Huile d’olive/20/ml/4;Parmesan/40/g/3",
    "Coupez finement oignon et carottes. Faites-les revenir 5 minutes dans l’huile.|Ajoutez le bœuf, émiettez-le et faites cuire 5 minutes. Versez les tomates et laissez mijoter 15 minutes.|Faites cuire les spaghetti dans une grande casserole d’eau selon le paquet.|Égouttez, mélangez à la sauce et servez avec le parmesan.",
  ),
  recipe(
    "quiche-lorraine",
    "Quiche lorraine & salade",
    "Une quiche dorée à partager, accompagnée de feuilles fraîches.",
    15,
    35,
    "all",
    "porc",
    "aucun",
    "tarte",
    "Pâte brisée/230/g/7;Lardons/180/g/1;Œufs/3/pièce/7;Crème/200/ml/3;Lait/100/ml/3;Salade verte/200/g/0;Huile d’olive/15/ml/4;Vinaigre/10/ml/4",
    "Préchauffez le four à 180 °C. Étalez la pâte dans un moule et piquez-la.|Faites revenir les lardons 5 minutes, égouttez-les et répartissez-les sur la pâte.|Battez les œufs avec la crème et le lait. Versez sur les lardons et enfournez 35 minutes.|Lavez et assaisonnez la salade avec l’huile et le vinaigre.",
    false,
  ),
  recipe(
    "saumon-four",
    "Saumon au four, riz & brocoli",
    "Un poisson tendre, du brocoli et un filet de citron, tout simplement.",
    10,
    20,
    "cold",
    "poisson",
    "riz",
    "four",
    "Saumon/600/g/2;Riz/280/g/5;Brocoli/600/g/0;Citron/1/pièce/0;Huile d’olive/20/ml/4",
    "Préchauffez le four à 180 °C. Placez le saumon dans un plat, arrosez d’huile et de jus de citron.|Faites cuire le riz selon les indications du paquet.|Détaillez le brocoli et faites-le cuire à la vapeur 10 minutes.|Enfournez le saumon 15 à 20 minutes jusqu’à cuisson à cœur. Vérifiez l’absence d’arêtes avant de servir.",
  ),
  recipe(
    "curry-poulet",
    "Curry doux de poulet",
    "Du lait de coco, des carottes et un curry tout doux pour toute la famille.",
    15,
    25,
    "all",
    "poulet",
    "riz",
    "mijoté",
    "Poulet/550/g/1;Riz/280/g/5;Carottes/350/g/0;Oignons/150/g/0;Lait de coco/400/ml/6;Curry doux/5/g/4;Huile d’olive/15/ml/4",
    "Émincez oignon et carottes, coupez le poulet en morceaux.|Faites revenir l’oignon dans l’huile 3 minutes. Ajoutez le poulet et faites dorer 5 minutes.|Ajoutez carottes, curry et lait de coco. Couvrez et mijotez 20 minutes, jusqu’à cuisson complète du poulet.|Cuisez le riz séparément puis servez le curry par-dessus.",
  ),
  recipe(
    "risotto-champignons",
    "Risotto aux champignons",
    "Un riz crémeux et des champignons bien dorés, sans vin.",
    15,
    30,
    "autumn",
    "végétarien",
    "riz",
    "mijoté",
    "Riz arborio/320/g/5;Champignons/500/g/0;Oignons/120/g/0;Eau/1000/ml/4;Parmesan/60/g/3;Beurre/25/g/3;Huile d’olive/15/ml/4",
    "Émincez les champignons et l’oignon. Faites dorer les champignons dans l’huile pendant 8 minutes puis réservez.|Faites fondre la moitié du beurre et faites revenir l’oignon 3 minutes. Ajoutez le riz et remuez 2 minutes.|Versez l’eau chaude salée louche par louche en remuant. Attendez l’absorption entre chaque ajout pendant 20 minutes.|Incorporez les champignons, le reste du beurre et le parmesan. Servez aussitôt.",
  ),
  recipe(
    "croque-monsieur",
    "Croque-monsieur & crudités",
    "Du pain croustillant, du jambon et du fromage fondant.",
    10,
    12,
    "all",
    "porc",
    "pain",
    "four",
    "Pain de mie/8/tranche/5;Jambon/4/tranche/1;Emmental/120/g/3;Beurre/20/g/3;Carottes/400/g/0;Salade verte/150/g/0;Huile d’olive/15/ml/4;Vinaigre/10/ml/4",
    "Préchauffez le four à 200 °C. Beurrez légèrement les tranches de pain.|Garnissez quatre tranches de jambon et de fromage, puis refermez les croques.|Enfournez 12 minutes en surveillant la coloration.|Râpez les carottes, lavez la salade et assaisonnez d’huile et de vinaigre.",
    false,
  ),
  recipe(
    "soupe-legumes",
    "Soupe de légumes & tartines",
    "Un velouté de légumes du marché, avec des tartines au fromage.",
    15,
    25,
    "cold",
    "végétarien",
    "pain",
    "soupe",
    "Carottes/350/g/0;Poireaux/300/g/0;Pommes de terre/300/g/0;Oignons/100/g/0;Eau/1000/ml/4;Pain/200/g/5;Comté/80/g/3;Huile d’olive/15/ml/4",
    "Épluchez les pommes de terre et les carottes. Nettoyez soigneusement les poireaux et émincez tous les légumes.|Faites revenir l’oignon dans l’huile 3 minutes. Ajoutez les légumes et l’eau, salez modérément.|Faites cuire 25 minutes, puis mixez jusqu’à obtenir un velouté.|Garnissez les tartines de comté et passez-les 5 minutes sous le gril en surveillant.",
  ),
  recipe(
    "tartiflette",
    "Tartiflette & salade",
    "Le plat montagnard à partager après une journée fraîche.",
    20,
    35,
    "winter",
    "porc",
    "pommes de terre",
    "gratin",
    "Pommes de terre/1000/g/0;Reblochon/300/g/3;Lardons/180/g/1;Oignons/200/g/0;Crème/100/ml/3;Salade verte/200/g/0;Huile d’olive/15/ml/4;Vinaigre/10/ml/4",
    "Faites cuire les pommes de terre à l’eau 20 minutes puis coupez-les en rondelles.|Faites revenir les oignons et les lardons 10 minutes. Préchauffez le four à 200 °C.|Mélangez pommes de terre, lardons, oignons et crème dans un plat. Posez le reblochon coupé en deux dessus.|Enfournez 20 minutes. Servez avec la salade lavée et assaisonnée.",
    false,
  ),
  recipe(
    "blanquette-veau",
    "Blanquette de veau",
    "Un mijoté tendre et une sauce onctueuse, sans alcool.",
    25,
    90,
    "cold",
    "veau",
    "riz",
    "mijoté",
    "Veau à mijoter/700/g/1;Carottes/400/g/0;Poireaux/250/g/0;Champignons/250/g/0;Oignons/150/g/0;Riz/280/g/5;Crème/150/ml/3;Farine/30/g/4;Beurre/30/g/3;Eau/1000/ml/4",
    "Coupez la viande et les légumes en gros morceaux. Mettez-les dans une cocotte avec l’eau, portez à frémissement et écumez.|Couvrez et laissez mijoter 75 minutes. Ajoutez les champignons pour les 15 dernières minutes.|Faites un roux avec beurre et farine. Ajoutez 500 ml de jus de cuisson puis la crème, fouettez et cuisez 5 minutes.|Versez la sauce sur la viande égouttée et servez avec le riz cuit à part.",
    false,
  ),
  recipe(
    "chili-carne",
    "Chili con carne doux",
    "Des haricots rouges, du bœuf et des épices douces à servir avec du riz.",
    15,
    30,
    "all",
    "bœuf",
    "riz",
    "mijoté",
    "Bœuf haché/450/g/1;Haricots rouges égouttés/500/g/6;Tomates concassées/500/g/6;Oignons/150/g/0;Riz/240/g/5;Cumin/4/g/4;Paprika doux/4/g/4;Huile d’olive/15/ml/4",
    "Faites revenir l’oignon émincé 5 minutes dans l’huile, puis ajoutez le bœuf et cuisez 5 minutes.|Ajoutez cumin, paprika et tomates. Laissez mijoter 20 minutes.|Rincez les haricots égouttés, ajoutez-les et réchauffez 10 minutes.|Faites cuire le riz séparément. Servez sans piment pour les enfants.",
  ),
  recipe(
    "papillote-poisson",
    "Papillotes de cabillaud",
    "Un poisson délicat cuit avec carottes, poireaux et citron.",
    15,
    25,
    "cold",
    "poisson",
    "pommes de terre",
    "vapeur",
    "Cabillaud/600/g/2;Poireaux/400/g/0;Carottes/300/g/0;Pommes de terre/600/g/0;Citron/1/pièce/0;Huile d’olive/20/ml/4",
    "Préchauffez le four à 180 °C. Émincez finement carottes et poireaux.|Répartissez les légumes sur quatre feuilles de papier cuisson. Ajoutez le poisson, l’huile et le citron.|Fermez les papillotes et enfournez 25 minutes. Vérifiez la cuisson à cœur et retirez les arêtes.|Faites cuire les pommes de terre à la vapeur 20 minutes et servez-les avec les papillotes.",
  ),
  recipe(
    "poulet-basquaise",
    "Poulet basquaise",
    "Une sauce tomate et poivrons parfumée, avec du riz.",
    20,
    40,
    "summer",
    "poulet",
    "riz",
    "mijoté",
    "Poulet/650/g/1;Poivrons/500/g/0;Tomates/500/g/0;Oignons/150/g/0;Ail/8/g/0;Riz/280/g/5;Huile d’olive/20/ml/4",
    "Coupez poivrons, tomates et oignon. Faites dorer le poulet 8 minutes dans l’huile et réservez.|Faites revenir oignon, ail et poivrons 8 minutes dans la même cocotte.|Ajoutez les tomates et le poulet, couvrez et mijotez 30 minutes jusqu’à cuisson complète.|Faites cuire le riz à part et servez avec la sauce.",
  ),
  recipe(
    "gratin-courgettes",
    "Gratin de courgettes au riz",
    "Un gratin doux au fromage, qui fait aimer les courgettes.",
    15,
    30,
    "summer",
    "végétarien",
    "riz",
    "gratin",
    "Courgettes/800/g/0;Riz/220/g/5;Œufs/2/pièce/7;Crème/150/ml/3;Emmental/80/g/3;Huile d’olive/15/ml/4",
    "Faites cuire le riz et égouttez-le. Préchauffez le four à 190 °C.|Râpez les courgettes et faites-les revenir 8 minutes dans l’huile pour évaporer leur eau.|Battez les œufs avec la crème, ajoutez le riz et les courgettes.|Versez dans un plat, parsemez d’emmental et enfournez 25 minutes.",
  ),
  recipe(
    "veloute-potimarron",
    "Velouté de potimarron & œuf",
    "Une soupe veloutée de saison, avec un œuf dur et du pain.",
    15,
    25,
    "autumn",
    "végétarien",
    "pain",
    "soupe",
    "Potimarron/900/g/0;Carottes/200/g/0;Oignons/100/g/0;Crème/100/ml/3;Œufs/4/pièce/7;Pain/200/g/5;Eau/900/ml/4;Huile d’olive/15/ml/4",
    "Lavez et épépinez le potimarron, puis coupez-le en dés. Épluchez les carottes et l’oignon.|Faites revenir l’oignon dans l’huile, ajoutez les légumes et l’eau. Cuisez 25 minutes.|Faites cuire les œufs 10 minutes dans l’eau bouillante, refroidissez et écalez.|Mixez la soupe avec la crème. Servez avec les œufs et des tranches de pain.",
  ),
  recipe(
    "pates-poireaux",
    "Pâtes aux poireaux & ricotta",
    "Des poireaux fondants et une sauce toute douce à la ricotta.",
    15,
    20,
    "cold",
    "végétarien",
    "pâtes",
    "poêlée",
    "Pâtes/350/g/5;Poireaux/600/g/0;Ricotta/250/g/3;Parmesan/40/g/3;Huile d’olive/20/ml/4",
    "Nettoyez les poireaux, émincez-les et faites-les fondre dans l’huile 15 minutes à couvert avec un peu d’eau.|Cuisez les pâtes selon le paquet et gardez une tasse d’eau de cuisson.|Ajoutez la ricotta aux poireaux. Détendez avec un peu d’eau de cuisson.|Mélangez les pâtes à la sauce et parsemez de parmesan.",
  ),
  recipe(
    "lentilles-carottes",
    "Lentilles mijotées aux carottes",
    "Un plat végétal complet et réconfortant, très simple à préparer.",
    15,
    30,
    "cold",
    "végétarien",
    "légumineuses",
    "mijoté",
    "Lentilles vertes/320/g/4;Carottes/500/g/0;Oignons/150/g/0;Tomates concassées/250/g/6;Eau/900/ml/4;Huile d’olive/20/ml/4;Thym/2/g/4",
    "Rincez les lentilles. Épluchez et coupez les carottes en rondelles, émincez l’oignon.|Faites revenir l’oignon 5 minutes dans l’huile. Ajoutez les carottes et les lentilles.|Versez l’eau, ajoutez les tomates et le thym puis mijotez 30 minutes.|Vérifiez la tendreté des lentilles, salez en fin de cuisson et ajoutez de l’eau si nécessaire.",
  ),
  recipe(
    "omelette-champignons",
    "Omelette aux champignons",
    "Une omelette moelleuse et une salade fraîche pour un soir pressé.",
    10,
    15,
    "autumn",
    "végétarien",
    "pain",
    "poêlée",
    "Œufs/8/pièce/7;Champignons/400/g/0;Beurre/20/g/3;Salade verte/200/g/0;Pain/200/g/5;Huile d’olive/15/ml/4;Vinaigre/10/ml/4",
    "Nettoyez et tranchez les champignons. Faites-les dorer 8 minutes dans le beurre.|Battez les œufs, versez-les sur les champignons et cuisez à feu doux jusqu’à ce qu’ils soient pris.|Repliez l’omelette et assurez une cuisson complète des œufs pour l’enfant.|Servez avec le pain et la salade assaisonnée.",
  ),
  recipe(
    "porc-moutarde",
    "Filet mignon à la moutarde",
    "Une viande tendre avec une sauce douce et des carottes.",
    15,
    30,
    "all",
    "porc",
    "pommes de terre",
    "mijoté",
    "Filet mignon de porc/650/g/1;Carottes/500/g/0;Pommes de terre/600/g/0;Crème/150/ml/3;Moutarde/25/g/4;Oignons/150/g/0;Huile d’olive/20/ml/4",
    "Coupez le filet mignon en médaillons, émincez l’oignon et tranchez les carottes.|Faites dorer la viande dans l’huile 5 minutes. Ajoutez oignon, carottes et 150 ml d’eau.|Couvrez et cuisez 25 minutes. Ajoutez moutarde et crème, puis réchauffez 5 minutes.|Cuisez les pommes de terre à la vapeur 20 minutes et servez avec la sauce.",
  ),
  recipe(
    "boulettes-tomate",
    "Boulettes de bœuf à la tomate",
    "Des boulettes tendres dans une sauce maison, avec de la semoule.",
    20,
    25,
    "all",
    "bœuf",
    "semoule",
    "mijoté",
    "Bœuf haché/500/g/1;Œufs/1/pièce/7;Chapelure/40/g/4;Tomates concassées/600/g/6;Oignons/150/g/0;Semoule/280/g/5;Huile d’olive/20/ml/4",
    "Mélangez le bœuf, l’œuf et la chapelure. Formez des boulettes de la taille d’une noix.|Faites revenir l’oignon dans l’huile, ajoutez les tomates et mijotez 10 minutes.|Déposez les boulettes dans la sauce, couvrez et faites cuire 20 minutes jusqu’à cuisson à cœur.|Préparez la semoule selon le paquet et servez avec la sauce.",
  ),
  recipe(
    "couscous-legumes",
    "Couscous de légumes",
    "Carottes, courgettes et pois chiches, parfumés aux épices douces.",
    20,
    30,
    "warm",
    "végétarien",
    "semoule",
    "mijoté",
    "Semoule/300/g/5;Pois chiches égouttés/400/g/6;Carottes/400/g/0;Courgettes/400/g/0;Tomates concassées/400/g/6;Oignons/150/g/0;Cumin/4/g/4;Huile d’olive/20/ml/4",
    "Coupez les légumes. Faites revenir l’oignon dans l’huile 5 minutes.|Ajoutez carottes, tomates, cumin et 400 ml d’eau. Cuisez 15 minutes.|Ajoutez courgettes et pois chiches rincés puis cuisez encore 15 minutes.|Préparez la semoule séparément et servez avec les légumes et leur jus.",
  ),
  recipe(
    "riz-cantonais",
    "Riz sauté aux petits pois",
    "Un riz sauté au jambon et à l’œuf, facile et familial.",
    15,
    20,
    "spring",
    "porc",
    "riz",
    "poêlée",
    "Riz/300/g/5;Petits pois/300/g/0;Jambon/200/g/1;Œufs/3/pièce/7;Carottes/200/g/0;Sauce soja/20/ml/4;Huile d’olive/20/ml/4",
    "Cuisez le riz selon le paquet puis égouttez-le soigneusement.|Coupez les carottes et le jambon en petits dés. Faites cuire carottes et petits pois 8 minutes dans l’eau.|Battez les œufs et faites-les cuire en brouillade dans une poêle avec la moitié de l’huile.|Ajoutez le reste de l’huile, le riz, les légumes et le jambon. Faites sauter 5 minutes et ajoutez la sauce soja.",
  ),
  recipe(
    "pates-epinards",
    "Pâtes aux épinards & fromage",
    "Une sauce crémeuse aux épinards et une touche de parmesan.",
    10,
    15,
    "spring",
    "végétarien",
    "pâtes",
    "poêlée",
    "Pâtes/350/g/5;Épinards/600/g/0;Crème/150/ml/3;Parmesan/60/g/3;Ail/5/g/0;Huile d’olive/15/ml/4",
    "Lavez les épinards. Faites revenir l’ail haché 1 minute dans l’huile.|Ajoutez les épinards et faites-les tomber 5 minutes. Versez la crème et chauffez doucement.|Cuisez les pâtes selon le paquet et gardez un peu d’eau de cuisson.|Mélangez pâtes et sauce, ajoutez le parmesan et ajustez la texture avec l’eau de cuisson.",
  ),
  recipe(
    "tarte-asperges",
    "Tarte aux asperges",
    "Une tarte printanière délicate, garnie d’asperges et de fromage.",
    20,
    35,
    "spring",
    "végétarien",
    "aucun",
    "tarte",
    "Pâte brisée/230/g/7;Asperges/600/g/0;Œufs/3/pièce/7;Crème/200/ml/3;Comté/80/g/3;Salade verte/200/g/0;Huile d’olive/15/ml/4;Vinaigre/10/ml/4",
    "Coupez les pieds fibreux des asperges et épluchez les blanches. Cuisez-les 8 minutes à la vapeur.|Préchauffez le four à 180 °C. Disposez la pâte dans un moule et piquez-la.|Battez œufs et crème, ajoutez le comté. Disposez les asperges sur la pâte et versez l’appareil.|Enfournez 35 minutes et servez avec la salade assaisonnée.",
  ),
  recipe(
    "poulet-citron",
    "Poulet au citron & petits pois",
    "Un poulet parfumé au citron, accompagné de petits pois et de riz.",
    15,
    25,
    "spring",
    "poulet",
    "riz",
    "poêlée",
    "Poulet/600/g/1;Petits pois/500/g/0;Riz/280/g/5;Citron/1/pièce/0;Oignons/150/g/0;Huile d’olive/20/ml/4",
    "Coupez le poulet en morceaux. Faites-le dorer 5 minutes dans l’huile.|Ajoutez l’oignon émincé, le jus de citron et 150 ml d’eau. Couvrez et cuisez 15 minutes.|Ajoutez les petits pois puis cuisez encore 10 minutes jusqu’à cuisson du poulet.|Faites cuire le riz à part et servez avec le jus.",
  ),
  recipe(
    "salade-pates",
    "Salade de pâtes méditerranéenne",
    "Des tomates juteuses, du concombre et de la feta pour les journées chaudes.",
    20,
    10,
    "summer",
    "végétarien",
    "pâtes",
    "salade",
    "Pâtes/320/g/5;Tomates/400/g/0;Concombre/300/g/0;Feta/180/g/3;Olives dénoyautées/60/g/6;Huile d’olive/30/ml/4;Citron/1/pièce/0",
    "Faites cuire les pâtes, égouttez et refroidissez-les rapidement sous l’eau froide.|Coupez les tomates et le concombre en dés. Émiettez la feta et coupez les olives.|Mélangez huile et jus de citron, puis réunissez tous les ingrédients.|Conservez au frais jusqu’au service. Coupez les morceaux à une taille adaptée à l’enfant.",
  ),
  recipe(
    "ratatouille-oeufs",
    "Ratatouille & œufs",
    "Les légumes d’été mijotés doucement, avec des œufs et du pain.",
    20,
    40,
    "summer",
    "végétarien",
    "pain",
    "mijoté",
    "Courgettes/400/g/0;Aubergines/350/g/0;Tomates/500/g/0;Poivrons/300/g/0;Oignons/150/g/0;Œufs/4/pièce/7;Pain/200/g/5;Huile d’olive/30/ml/4",
    "Coupez les légumes en dés. Faites revenir oignon et poivrons 8 minutes dans l’huile.|Ajoutez aubergines et courgettes et cuisez 8 minutes, puis ajoutez les tomates.|Couvrez et mijotez 25 minutes à feu doux.|Formez quatre creux dans les légumes et cassez-y les œufs. Couvrez jusqu’à cuisson complète et servez avec le pain.",
  ),
  recipe(
    "tomates-farcies",
    "Tomates farcies",
    "De belles tomates garnies de viande et accompagnées de riz.",
    20,
    40,
    "summer",
    "porc",
    "riz",
    "four",
    "Tomates/1000/g/0;Porc haché/450/g/1;Riz/280/g/5;Oignons/100/g/0;Ail/5/g/0;Chapelure/40/g/4;Huile d’olive/20/ml/4",
    "Préchauffez le four à 180 °C. Coupez le chapeau des tomates et évidez-les en gardant la chair.|Mélangez viande, oignon et ail hachés, chapelure et chair de tomate.|Garnissez les tomates, placez-les dans un plat et arrosez d’huile. Enfournez 40 minutes jusqu’à cuisson complète de la farce.|Cuisez le riz à part et servez avec le jus du plat.",
  ),
  recipe(
    "salade-riz-thon",
    "Salade de riz au thon",
    "Un repas frais avec du thon, des tomates et du maïs.",
    15,
    15,
    "summer",
    "poisson",
    "riz",
    "salade",
    "Riz/280/g/5;Thon égoutté/300/g/6;Tomates/400/g/0;Concombre/300/g/0;Maïs égoutté/200/g/6;Huile d’olive/30/ml/4;Citron/1/pièce/0",
    "Faites cuire le riz puis refroidissez-le rapidement en l’étalant dans un plat peu profond.|Coupez tomates et concombre en dés. Égouttez le maïs et émiettez le thon.|Mélangez l’huile et le jus de citron puis réunissez tous les ingrédients.|Placez immédiatement au frais et servez le jour même.",
  ),
  recipe(
    "aubergines-parmesan",
    "Aubergines à la parmigiana",
    "Des aubergines rôties, de la tomate et une mozzarella fondante.",
    25,
    40,
    "summer",
    "végétarien",
    "pain",
    "gratin",
    "Aubergines/900/g/0;Tomates concassées/600/g/6;Mozzarella/250/g/3;Parmesan/60/g/3;Ail/8/g/0;Huile d’olive/30/ml/4;Pain/200/g/5",
    "Coupez les aubergines en tranches, badigeonnez d’huile et rôtissez 20 minutes à 200 °C.|Faites mijoter les tomates avec l’ail haché 10 minutes.|Alternez aubergines, sauce, mozzarella et parmesan dans un plat.|Enfournez 25 minutes à 190 °C. Servez avec du pain.",
    false,
  ),
  recipe(
    "taboule-pois-chiches",
    "Taboulé aux pois chiches",
    "Une salade colorée et rassasiante, au citron et aux légumes croquants.",
    20,
    5,
    "summer",
    "végétarien",
    "semoule",
    "salade",
    "Semoule/280/g/5;Pois chiches égouttés/400/g/6;Tomates/400/g/0;Concombre/300/g/0;Citron/1/pièce/0;Huile d’olive/30/ml/4;Persil/15/g/0",
    "Réhydratez la semoule selon le paquet puis égrainez et laissez refroidir.|Coupez les tomates et le concombre en petits dés. Rincez les pois chiches.|Hachez le persil et mélangez-le avec l’huile et le jus de citron.|Réunissez les ingrédients et conservez au frais jusqu’au service.",
  ),
  recipe(
    "gratin-chou-fleur",
    "Gratin de chou-fleur & œufs",
    "Un chou-fleur nappé de béchamel, avec des œufs durs.",
    20,
    25,
    "cold",
    "végétarien",
    "aucun",
    "gratin",
    "Chou-fleur/1000/g/0;Œufs/4/pièce/7;Lait/500/ml/3;Farine/40/g/4;Beurre/40/g/3;Emmental/80/g/3",
    "Détaillez le chou-fleur et cuisez-le à la vapeur 15 minutes.|Cuisez les œufs 10 minutes à l’eau bouillante, puis écalez-les.|Préparez la béchamel : faites fondre le beurre, ajoutez la farine puis le lait progressivement et fouettez 5 minutes.|Disposez chou-fleur et œufs coupés dans un plat, nappez de sauce, parsemez de fromage et gratinez 20 minutes à 200 °C.",
    false,
  ),
  recipe(
    "endives-jambon",
    "Endives au jambon",
    "Des endives fondantes sous une sauce gratinée.",
    20,
    35,
    "winter",
    "porc",
    "aucun",
    "gratin",
    "Endives/800/g/0;Jambon/4/tranche/1;Lait/500/ml/3;Farine/40/g/4;Beurre/40/g/3;Emmental/80/g/3",
    "Retirez la base amère des endives et faites-les cuire 20 minutes à la vapeur. Égouttez-les très soigneusement.|Préparez une béchamel avec beurre, farine puis lait en fouettant 5 minutes.|Enroulez chaque endive dans le jambon et déposez dans un plat.|Nappez de béchamel et de fromage puis enfournez 25 minutes à 190 °C.",
    false,
  ),
  recipe(
    "saucisses-lentilles",
    "Saucisses aux lentilles",
    "Un plat de cocotte généreux, avec des carottes et du thym.",
    15,
    35,
    "cold",
    "porc",
    "légumineuses",
    "mijoté",
    "Saucisses de porc/400/g/1;Lentilles vertes/300/g/4;Carottes/400/g/0;Oignons/150/g/0;Thym/2/g/4;Huile d’olive/15/ml/4;Eau/1000/ml/4",
    "Rincez les lentilles, émincez l’oignon et coupez les carottes.|Faites revenir oignon et saucisses 5 minutes dans l’huile.|Ajoutez lentilles, carottes, thym et eau. Couvrez et mijotez 30 à 35 minutes.|Vérifiez la cuisson complète des saucisses et la tendreté des lentilles. Coupez la saucisse en longueur puis en petits morceaux pour l’enfant.",
    false,
  ),
  recipe(
    "boeuf-carottes",
    "Bœuf braisé aux carottes",
    "Une cocotte du dimanche sans vin, à laisser mijoter tranquillement.",
    20,
    120,
    "cold",
    "bœuf",
    "pommes de terre",
    "mijoté",
    "Bœuf à braiser/750/g/1;Carottes/800/g/0;Oignons/200/g/0;Pommes de terre/600/g/0;Tomates concassées/300/g/6;Thym/2/g/4;Huile d’olive/20/ml/4;Eau/700/ml/4",
    "Faites dorer le bœuf coupé en gros dés dans l’huile pendant 8 minutes.|Ajoutez les oignons émincés puis les carottes, les tomates, le thym et l’eau.|Couvrez et mijotez 2 heures à feu très doux, jusqu’à ce que la viande soit tendre. Ajoutez un peu d’eau si nécessaire.|Cuisez les pommes de terre à part à la vapeur et servez avec le jus.",
  ),
  recipe(
    "poelee-potiron",
    "Poêlée de courge & pois chiches",
    "Des dés de courge dorés avec des pois chiches et de la semoule.",
    15,
    25,
    "autumn",
    "végétarien",
    "semoule",
    "poêlée",
    "Courge/800/g/0;Pois chiches égouttés/400/g/6;Semoule/240/g/5;Oignons/150/g/0;Cumin/4/g/4;Huile d’olive/25/ml/4",
    "Épluchez et épépinez la courge puis coupez-la en petits dés.|Faites revenir l’oignon 5 minutes dans l’huile. Ajoutez la courge, le cumin et 100 ml d’eau.|Couvrez 15 minutes, puis ajoutez les pois chiches rincés et cuisez 5 minutes sans couvercle.|Préparez la semoule selon le paquet et servez avec la poêlée.",
  ),
  recipe(
    "tarte-poireaux",
    "Tarte aux poireaux & chèvre",
    "Une tarte crémeuse aux poireaux fondants.",
    20,
    35,
    "cold",
    "végétarien",
    "aucun",
    "tarte",
    "Pâte brisée/230/g/7;Poireaux/700/g/0;Fromage de chèvre/150/g/3;Œufs/3/pièce/7;Crème/150/ml/3;Huile d’olive/15/ml/4",
    "Nettoyez les poireaux et émincez-les. Faites-les fondre 15 minutes dans l’huile à couvert.|Préchauffez le four à 180 °C. Étalez la pâte dans un moule.|Battez œufs et crème, ajoutez les poireaux et versez sur la pâte.|Disposez le chèvre en rondelles et enfournez 35 minutes.",
  ),
  recipe(
    "poulet-champignons",
    "Poulet aux champignons",
    "Une sauce crémeuse légère avec du riz et des champignons dorés.",
    15,
    25,
    "autumn",
    "poulet",
    "riz",
    "poêlée",
    "Poulet/600/g/1;Champignons/500/g/0;Riz/280/g/5;Crème/150/ml/3;Oignons/150/g/0;Huile d’olive/20/ml/4",
    "Coupez le poulet, émincez les champignons et l’oignon.|Faites dorer le poulet dans l’huile 5 minutes et réservez. Faites revenir oignon et champignons 8 minutes.|Remettez le poulet, ajoutez crème et 100 ml d’eau. Couvrez et cuisez 15 minutes jusqu’à cuisson complète.|Cuisez le riz à part et servez avec la sauce.",
  ),
  recipe(
    "colin-carottes",
    "Colin, purée de carottes",
    "Un poisson tout doux avec une purée orange et moelleuse.",
    15,
    25,
    "all",
    "poisson",
    "pommes de terre",
    "vapeur",
    "Colin/600/g/2;Carottes/600/g/0;Pommes de terre/500/g/0;Lait/150/ml/3;Beurre/20/g/3;Citron/1/pièce/0",
    "Épluchez les légumes, coupez-les et faites-les cuire à l’eau 25 minutes.|Faites cuire le colin à la vapeur 12 à 15 minutes jusqu’à cuisson à cœur.|Égouttez les légumes et écrasez-les avec le lait chaud et le beurre.|Retirez toutes les arêtes du poisson et servez avec un peu de jus de citron.",
  ),
  recipe(
    "nouilles-poulet",
    "Nouilles sautées au poulet",
    "Des nouilles et des légumes croquants dans une sauce douce.",
    20,
    15,
    "all",
    "poulet",
    "pâtes",
    "poêlée",
    "Nouilles de blé/300/g/5;Poulet/500/g/1;Carottes/400/g/0;Chou blanc/300/g/0;Sauce soja/25/ml/4;Huile d’olive/20/ml/4",
    "Coupez le poulet en fines lanières et les légumes en bâtonnets.|Cuisez les nouilles selon le paquet puis égouttez-les.|Faites dorer le poulet dans l’huile 6 minutes puis ajoutez les légumes et cuisez 7 minutes.|Ajoutez les nouilles et la sauce soja, faites sauter 2 minutes et vérifiez la cuisson du poulet.",
  ),
  recipe(
    "dahl-lentilles",
    "Dahl de lentilles corail",
    "Un mijoté végétal au lait de coco, parfumé sans piquant.",
    10,
    25,
    "all",
    "végétarien",
    "riz",
    "mijoté",
    "Lentilles corail/300/g/4;Riz/240/g/5;Carottes/400/g/0;Lait de coco/300/ml/6;Tomates concassées/300/g/6;Oignons/150/g/0;Curry doux/4/g/4;Huile d’olive/15/ml/4",
    "Rincez les lentilles, râpez les carottes et émincez l’oignon.|Faites revenir l’oignon et le curry dans l’huile 3 minutes.|Ajoutez lentilles, carottes, tomates, lait de coco et 400 ml d’eau. Mijotez 25 minutes en remuant.|Cuisez le riz à part. Ajoutez de l’eau au dahl si besoin et servez.",
  ),
  recipe(
    "chili-sin-carne",
    "Chili végétarien",
    "Haricots rouges et maïs dans une sauce tomate aux épices douces.",
    10,
    25,
    "all",
    "végétarien",
    "riz",
    "mijoté",
    "Haricots rouges égouttés/600/g/6;Maïs égoutté/200/g/6;Tomates concassées/500/g/6;Carottes/300/g/0;Oignons/150/g/0;Riz/250/g/5;Cumin/4/g/4;Huile d’olive/20/ml/4",
    "Émincez l’oignon et coupez les carottes en petits dés. Faites-les revenir 5 minutes dans l’huile.|Ajoutez les tomates, le cumin et 100 ml d’eau puis cuisez 15 minutes.|Ajoutez les haricots rincés et le maïs égoutté. Mijotez encore 10 minutes.|Cuisez le riz selon le paquet et servez avec le chili.",
  ),
  recipe(
    "gnocchis-epinards",
    "Gnocchis aux épinards",
    "Des gnocchis tendres dans une sauce aux épinards et à la crème.",
    10,
    15,
    "spring",
    "végétarien",
    "pommes de terre",
    "poêlée",
    "Gnocchis/600/g/5;Épinards/500/g/0;Crème/150/ml/3;Parmesan/50/g/3;Huile d’olive/15/ml/4",
    "Lavez les épinards et faites-les tomber 5 minutes dans l’huile.|Ajoutez la crème et laissez chauffer 3 minutes.|Cuisez les gnocchis à l’eau selon le paquet et égouttez dès qu’ils remontent.|Mélangez avec la sauce, ajoutez le parmesan et servez immédiatement.",
  ),
  recipe(
    "frittata-legumes",
    "Frittata aux légumes d’été",
    "Une omelette épaisse au four, colorée et simple à partager.",
    15,
    25,
    "summer",
    "végétarien",
    "pommes de terre",
    "four",
    "Œufs/8/pièce/7;Courgettes/400/g/0;Tomates/300/g/0;Pommes de terre/400/g/0;Oignons/100/g/0;Huile d’olive/20/ml/4",
    "Préchauffez le four à 180 °C. Coupez les pommes de terre en petits dés et cuisez-les 10 minutes à l’eau.|Faites revenir oignon et courgettes en dés dans l’huile 8 minutes.|Battez les œufs, ajoutez tous les légumes et versez dans un plat huilé.|Enfournez 25 minutes jusqu’à ce que les œufs soient complètement pris.",
  ),
  recipe(
    "pates-thon",
    "Pâtes au thon & tomate",
    "Un repas du placard prêt en vingt-cinq minutes.",
    10,
    15,
    "all",
    "poisson",
    "pâtes",
    "poêlée",
    "Pâtes/350/g/5;Thon égoutté/300/g/6;Tomates concassées/500/g/6;Oignons/150/g/0;Huile d’olive/20/ml/4;Ail/5/g/0",
    "Faites revenir l’oignon et l’ail hachés dans l’huile 5 minutes.|Ajoutez les tomates et mijotez 10 minutes.|Cuisez les pâtes à part selon le paquet. Émiettez le thon dans la sauce et réchauffez 2 minutes.|Mélangez les pâtes égouttées et la sauce puis servez.",
  ),
  recipe(
    "saumon-courgettes",
    "Saumon & courgettes rôties",
    "Un plat au four lumineux, avec du boulgour et du citron.",
    15,
    25,
    "summer",
    "poisson",
    "boulgour",
    "four",
    "Saumon/600/g/2;Courgettes/800/g/0;Boulgour/280/g/5;Citron/1/pièce/0;Huile d’olive/25/ml/4",
    "Préchauffez le four à 190 °C. Coupez les courgettes en demi-rondelles, huilez-les et enfournez 10 minutes.|Ajoutez le saumon, arrosez de citron et cuisez encore 15 à 20 minutes.|Faites cuire le boulgour selon le paquet.|Vérifiez la cuisson à cœur du saumon et retirez les arêtes avant de servir.",
  ),
  recipe(
    "poulet-pommes",
    "Poulet aux pommes",
    "Des pommes fondantes et une sauce douce pour une assiette d’automne.",
    15,
    30,
    "autumn",
    "poulet",
    "pommes de terre",
    "mijoté",
    "Poulet/600/g/1;Pommes/400/g/0;Pommes de terre/700/g/0;Oignons/150/g/0;Crème/150/ml/3;Huile d’olive/20/ml/4",
    "Coupez le poulet en morceaux et faites-le dorer 5 minutes dans l’huile.|Ajoutez l’oignon et les pommes en quartiers, puis 150 ml d’eau. Couvrez et cuisez 25 minutes.|Ajoutez la crème et réchauffez doucement. Vérifiez la cuisson complète du poulet.|Cuisez les pommes de terre à la vapeur et servez avec la sauce.",
  ),
  recipe(
    "gratin-butternut",
    "Gratin de butternut & lentilles",
    "La douceur de la courge avec des lentilles et une croûte gratinée.",
    20,
    35,
    "autumn",
    "végétarien",
    "légumineuses",
    "gratin",
    "Courge butternut/900/g/0;Lentilles vertes/250/g/4;Crème/150/ml/3;Comté/80/g/3;Oignons/150/g/0;Huile d’olive/20/ml/4",
    "Cuisez les lentilles rincées 25 minutes dans l’eau et égouttez.|Épluchez la courge, coupez-la en dés et faites-la cuire à la vapeur 15 minutes.|Faites revenir l’oignon dans l’huile puis mélangez-le aux lentilles, à la courge et à la crème.|Versez dans un plat, parsemez de comté et gratinez 20 minutes à 190 °C.",
  ),
  recipe(
    "soupe-chou",
    "Soupe de chou & haricots blancs",
    "Une soupe rustique nourrissante, avec des légumes et des haricots.",
    15,
    30,
    "winter",
    "végétarien",
    "légumineuses",
    "soupe",
    "Chou vert/600/g/0;Carottes/300/g/0;Pommes de terre/300/g/0;Haricots blancs égouttés/500/g/6;Oignons/150/g/0;Eau/1200/ml/4;Huile d’olive/20/ml/4",
    "Émincez le chou et l’oignon, coupez carottes et pommes de terre en dés.|Faites revenir l’oignon dans l’huile 3 minutes puis ajoutez les légumes.|Versez l’eau et faites cuire 25 minutes à frémissement.|Ajoutez les haricots rincés et réchauffez 5 minutes. Ajustez l’assaisonnement et servez.",
  ),
  recipe(
    "tofu-brocoli",
    "Tofu doré & brocoli",
    "Un plat végétal doux, avec du riz et une sauce soja légère.",
    15,
    20,
    "cold",
    "végétarien",
    "riz",
    "poêlée",
    "Tofu nature/500/g/7;Brocoli/700/g/0;Riz/280/g/5;Sauce soja/20/ml/4;Huile d’olive/25/ml/4",
    "Égouttez et séchez le tofu puis coupez-le en dés.|Faites cuire le brocoli en fleurettes à la vapeur 10 minutes et le riz selon le paquet.|Faites dorer le tofu dans l’huile 10 minutes en retournant les dés.|Ajoutez le brocoli et la sauce soja, mélangez 2 minutes puis servez avec le riz.",
  ),
  recipe(
    "galettes-lentilles",
    "Galettes de lentilles & carottes",
    "Des galettes moelleuses, une sauce au yaourt et une salade.",
    25,
    20,
    "all",
    "végétarien",
    "légumineuses",
    "poêlée",
    "Lentilles corail/250/g/4;Carottes/300/g/0;Œufs/2/pièce/7;Farine/60/g/4;Yaourt/150/g/3;Salade verte/200/g/0;Huile d’olive/25/ml/4;Citron/1/pièce/0",
    "Cuisez les lentilles 12 minutes puis égouttez-les très soigneusement. Râpez les carottes.|Mélangez lentilles, carottes, œufs et farine puis formez de petites galettes.|Faites cuire dans l’huile 4 à 5 minutes de chaque côté jusqu’à cuisson complète.|Mélangez yaourt et citron et servez avec les galettes et la salade lavée.",
  ),
  recipe(
    "truite-four",
    "Truite au four & carottes",
    "Des filets de truite citronnés, avec des légumes vapeur.",
    10,
    25,
    "all",
    "poisson",
    "pommes de terre",
    "four",
    "Truite/600/g/2;Carottes/500/g/0;Pommes de terre/600/g/0;Citron/1/pièce/0;Huile d’olive/20/ml/4",
    "Préchauffez le four à 180 °C. Épluchez les légumes et coupez-les en morceaux.|Cuisez les pommes de terre et les carottes à la vapeur 25 minutes.|Déposez les filets dans un plat, ajoutez huile et citron et enfournez 15 à 20 minutes.|Vérifiez la cuisson et retirez soigneusement les arêtes avant de servir.",
  ),
  recipe(
    "poulet-semoule",
    "Poulet aux carottes & semoule",
    "Un mijoté simple au cumin, prêt pour un dîner de semaine.",
    15,
    25,
    "all",
    "poulet",
    "semoule",
    "mijoté",
    "Poulet/600/g/1;Carottes/600/g/0;Semoule/280/g/5;Oignons/150/g/0;Cumin/3/g/4;Huile d’olive/20/ml/4",
    "Coupez le poulet et les carottes, émincez l’oignon.|Faites revenir l’oignon et le poulet dans l’huile 5 minutes.|Ajoutez les carottes, le cumin et 250 ml d’eau. Couvrez et cuisez 25 minutes jusqu’à cuisson complète du poulet.|Préparez la semoule selon le paquet et servez avec le jus.",
  ),
  recipe(
    "salade-lentilles",
    "Salade de lentilles & feta",
    "Des lentilles, des carottes croquantes et une vinaigrette à la moutarde.",
    15,
    25,
    "all",
    "végétarien",
    "légumineuses",
    "salade",
    "Lentilles vertes/300/g/4;Carottes/350/g/0;Feta/180/g/3;Salade verte/150/g/0;Moutarde/15/g/4;Huile d’olive/30/ml/4;Vinaigre/15/ml/4",
    "Faites cuire les lentilles rincées dans l’eau 25 minutes puis égouttez et laissez tiédir.|Râpez les carottes, lavez la salade et émiettez la feta.|Fouettez moutarde, huile et vinaigre.|Mélangez les lentilles et les carottes à la sauce puis ajoutez feta et salade.",
  ),
  recipe(
    "soupe-petits-pois",
    "Velouté de petits pois & tartines",
    "Un velouté vert tout doux avec des tartines au fromage.",
    10,
    20,
    "spring",
    "végétarien",
    "pain",
    "soupe",
    "Petits pois/800/g/0;Pommes de terre/250/g/0;Oignons/100/g/0;Eau/900/ml/4;Crème/100/ml/3;Pain/200/g/5;Comté/80/g/3;Huile d’olive/15/ml/4",
    "Faites revenir l’oignon émincé dans l’huile 3 minutes.|Ajoutez pommes de terre en dés, petits pois et eau. Cuisez 20 minutes.|Mixez avec la crème et ajoutez un peu d’eau si nécessaire.|Garnissez le pain de comté et passez 5 minutes au gril en surveillant.",
  ),
  recipe(
    "boulgour-legumes",
    "Boulgour aux légumes rôtis",
    "Des légumes d’été rôtis et de la feta sur un lit de boulgour.",
    15,
    30,
    "summer",
    "végétarien",
    "boulgour",
    "four",
    "Boulgour/300/g/5;Courgettes/400/g/0;Aubergines/350/g/0;Poivrons/300/g/0;Feta/180/g/3;Huile d’olive/30/ml/4",
    "Préchauffez le four à 200 °C. Coupez les légumes en dés réguliers.|Étalez-les sur une plaque, arrosez d’huile et enfournez 30 minutes en remuant à mi-cuisson.|Cuisez le boulgour selon le paquet et égouttez.|Répartissez les légumes sur le boulgour et ajoutez la feta émiettée.",
  ),
  recipe(
    "tortilla-pommes-terre",
    "Tortilla aux pommes de terre",
    "Une omelette espagnole épaisse avec une salade de carottes.",
    20,
    25,
    "all",
    "végétarien",
    "pommes de terre",
    "poêlée",
    "Pommes de terre/700/g/0;Œufs/6/pièce/7;Oignons/150/g/0;Carottes/400/g/0;Huile d’olive/35/ml/4;Vinaigre/10/ml/4",
    "Épluchez et coupez les pommes de terre en fines rondelles. Faites-les cuire 15 minutes à couvert dans 25 ml d’huile avec l’oignon émincé.|Battez les œufs et mélangez-les aux pommes de terre tiédies.|Versez dans une poêle antiadhésive et cuisez à feu doux 7 minutes. Retournez avec une assiette et cuisez 5 minutes, jusqu’à cuisson complète.|Râpez les carottes et assaisonnez du reste d’huile et du vinaigre.",
  ),
];
